#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_CSS_CANDIDATES = [
    "app/globals.css",
    "src/app/globals.css",
    "styles/globals.css",
    "src/styles/globals.css",
    "app.css",
    "src/app.css",
    "src/index.css",
]

MARKER_START = "/* codex-design-autopilot:start */"
MARKER_END = "/* codex-design-autopilot:end */"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply bounded deterministic CSS fixes from design audit findings.")
    parser.add_argument("--root", default=".", help="Project root.")
    parser.add_argument(
        "--audit-file",
        default=None,
        help="Path to design audit JSON. Defaults to .playwright-gate/design-audit.json.",
    )
    parser.add_argument("--iteration", type=int, default=1)
    parser.add_argument("--output", default=None, help="Path for autofix report JSON.")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True), encoding="utf-8")


def find_css_target(root: Path) -> Path | None:
    for candidate in DEFAULT_CSS_CANDIDATES:
        path = root / candidate
        if path.exists() and path.is_file():
            return path
    return None


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def extract_warn_ids(findings: list[dict[str, Any]]) -> set[str]:
    warn_ids: set[str] = set()
    for finding in findings:
        if finding.get("status") == "warn" and finding.get("id"):
            warn_ids.add(str(finding["id"]))
    return warn_ids


def build_fix_block(warn_ids: set[str]) -> tuple[str, list[str], list[str]]:
    applied: list[str] = []
    unsupported: list[str] = []
    lines: list[str] = [MARKER_START]
    lines.append("/* Generated by design_autofix_orchestrator.py. Keep this block managed. */")

    layout_signals = {
        "overflow-horizontal",
        "overlap-detected",
        "truncated-headings",
        "heading-hierarchy-inconsistent",
    }
    if warn_ids.intersection(layout_signals):
        applied.append("layout-overflow-wrap")
        lines.extend(
            [
                "html, body {",
                "  max-width: 100%;",
                "  overflow-x: clip;",
                "}",
                "*, *::before, *::after {",
                "  box-sizing: border-box;",
                "}",
                "img, svg, video, canvas, iframe {",
                "  max-width: 100%;",
                "  height: auto;",
                "}",
                "h1, h2, h3, h4, h5, h6, p, a, button {",
                "  overflow-wrap: anywhere;",
                "  word-break: break-word;",
                "}",
                "main, section, article, .container, .content {",
                "  min-width: 0;",
                "}",
            ]
        )

    if "contrast-low" in warn_ids:
        applied.append("contrast-fallback")
        lines.extend(
            [
                ":root {",
                "  --autopilot-text: #111827;",
                "  --autopilot-bg: #ffffff;",
                "  --autopilot-link: #1d4ed8;",
                "}",
                "body {",
                "  color: var(--autopilot-text);",
                "  background-color: var(--autopilot-bg);",
                "}",
                "a {",
                "  color: var(--autopilot-link);",
                "}",
            ]
        )

    focus_signals = {"focus-states-invisible"}
    if warn_ids.intersection(focus_signals):
        applied.append("focus-visible")
        lines.extend(
            [
                ":focus-visible {",
                "  outline: 2px solid #2563eb !important;",
                "  outline-offset: 2px;",
                "}",
            ]
        )

    motion_signals = {"animations-too-aggressive", "reduced-motion-not-configured"}
    if warn_ids.intersection(motion_signals):
        applied.append("reduced-motion")
        lines.extend(
            [
                "@media (prefers-reduced-motion: reduce) {",
                "  *, *::before, *::after {",
                "    animation-duration: 0.01ms !important;",
                "    animation-iteration-count: 1 !important;",
                "    transition-duration: 0.01ms !important;",
                "    scroll-behavior: auto !important;",
                "  }",
                "}",
            ]
        )

    unsupported_signals = {
        "cta-critical-offscreen-mobile",
        "console-errors-blocking",
        "page-load-failed",
        "page-http-error",
    }
    for finding_id in sorted(warn_ids.intersection(unsupported_signals)):
        unsupported.append(finding_id)

    lines.append(MARKER_END)
    return "\n".join(lines) + "\n", applied, unsupported


def apply_managed_block(css_text: str, new_block: str) -> tuple[str, bool]:
    if MARKER_START in css_text and MARKER_END in css_text:
        start = css_text.index(MARKER_START)
        end = css_text.index(MARKER_END, start) + len(MARKER_END)
        before = css_text[:start].rstrip() + "\n\n"
        after = css_text[end:].lstrip("\n")
        updated = before + new_block
        if after:
            updated += "\n" + after
        return updated, True

    spacer = "\n" if css_text.endswith("\n") else "\n\n"
    return css_text + spacer + new_block, False


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    audit_file = (
        Path(args.audit_file).resolve()
        if args.audit_file
        else root / ".playwright-gate" / "design-audit.json"
    )
    output_path = (
        Path(args.output).resolve()
        if args.output
        else root / ".playwright-gate" / "autofix-report.json"
    )

    if not audit_file.exists():
        payload = {
            "status": "failed",
            "timestamp": now_iso(),
            "reason": f"Audit file not found: {audit_file}",
            "changed": False,
        }
        write_json(output_path, payload)
        if args.json:
            print(json.dumps(payload, ensure_ascii=True))
        else:
            print(f"status={payload['status']}")
            print(f"reason={payload['reason']}")
        return 1

    audit = load_json(audit_file)
    findings = audit.get("findings", [])
    warn_ids = extract_warn_ids(findings if isinstance(findings, list) else [])

    css_target = find_css_target(root)
    if css_target is None:
        payload = {
            "status": "failed",
            "timestamp": now_iso(),
            "iteration": args.iteration,
            "reason": "No supported global CSS target was found.",
            "changed": False,
            "applied_fixes": [],
            "unsupported_findings": sorted(warn_ids),
        }
        write_json(output_path, payload)
        if args.json:
            print(json.dumps(payload, ensure_ascii=True))
        else:
            print("status=failed")
            print("reason=No supported global CSS target was found")
        return 1

    css_before = css_target.read_text(encoding="utf-8", errors="ignore")
    hash_before = sha256_text(css_before)

    fix_block, applied_fixes, unsupported_findings = build_fix_block(warn_ids)
    css_after, replaced_existing_block = apply_managed_block(css_before, fix_block)
    hash_after = sha256_text(css_after)

    changed = hash_before != hash_after
    if changed:
        css_target.write_text(css_after, encoding="utf-8")

    status = "fixed" if changed else "no_diff"
    payload = {
        "status": status,
        "timestamp": now_iso(),
        "iteration": args.iteration,
        "changed": changed,
        "target_css": str(css_target),
        "replaced_existing_block": replaced_existing_block,
        "applied_fixes": applied_fixes,
        "unsupported_findings": unsupported_findings,
        "hash_before": hash_before,
        "hash_after": hash_after,
    }

    write_json(output_path, payload)

    if args.json:
        print(json.dumps(payload, ensure_ascii=True))
    else:
        print(f"status={status}")
        print(f"changed={str(changed).lower()}")
        print(f"target_css={css_target}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
